v1 of swagger,
Master-Trolls-of-IT/PLIC-back pull request #14
Opened 2023-05-29 16:34 UTC by lesageduvillage

pr pour le swagger les amis, il faudra suivre la syntaxe sur les prochains endpoints

2023-05-29 16:48 UTC, lesageduvillage commented
@AymanImhah c'est bon tu peux vérif si tu veux

2023-05-29 17:29 UTC, AymanImhah requested changes
Met le dossiers docs dans infrastructure

2023-05-29 17:29 UTC, AymanImhah commented on docs/swagger.yaml
> +host: plic-back-qp6wugltyq-ew.a.run.app/
ya cette erreur la sur le swagger : 
![image](https://github.com/Master-Trolls-of-IT/PLIC-back/assets/124256635/103ac8b1-d321-4c01-9670-fdfca693deb4)

2023-05-29 17:29 UTC, AymanImhah commented on docs/swagger.json
> +                "description": "Register function that returns a JSON with this structure : { \"message\": \"User registered successfully\" }",
ya pas moyen de formatter le  { \"message\": \"User registered successfully\" }" ? ou genre mettre les responses en struct dans un autre fichier ?

2023-05-29 17:31 UTC, lesageduvillage commented on docs/swagger.json
> +                "description": "Register function that returns a JSON with this structure : { \"message\": \"User registered successfully\" }",
faudrait que je teste de mettre la réponse en struct ouai, psk les ' ' marchent pas il me semble

2023-06-12 16:11 UTC, lesageduvillage commented
> Met le dossiers docs dans infrastructure

je peux pas c'est généré automaitquement par swaggo dans le dossier docs à la racine du projet

2023-06-12 16:12 UTC, AymanImhah approved these changes

2023-06-12 16:12 UTC, merged