Consumed products endpoint
Master-Trolls-of-IT/PLIC-back pull request #18
Opened 2023-07-08 11:37 UTC by lesageduvillage

pr pour faire la page de produits consommés

2023-07-08 11:52 UTC, Uzayur approved these changes

2023-07-08 22:08 UTC, AymanImhah requested changes

2023-07-08 22:08 UTC, AymanImhah commented on infrastructure/controller/api.go
> +func (server *Server) getConsumedProducts(context *gin.Context) {
il faut aussi prendre en considération la date : 
 date := context.Query("date")
 
 comme ca depuis le front on peut envoyer la date aussi comme suit  :   /product/consumed/user/:email?date='exemple'
 et si date est nil , tu considère que c'est celle d'aujourd'hui.
 
 il faut mettre a jour ton code pour intégrer la date du coup (dans le Post aussi)

2023-07-08 22:08 UTC, AymanImhah commented on infrastructure/controller/api.go
> +	}
Vu que dans cette MR on prend pas en considération la quantité , si tu peux le mentionner dans la description de la MR stp , pour Tommy et Mathisou

2023-07-08 22:08 UTC, AymanImhah commented on infrastructure/repository/product_repository.go
> +	rows, err := database.Query("SELECT p.id, p.name, p.energy_kj, p.energy_kcal, p.fat, p.saturated_fat, p.sugar, p.fiber, p.proteins, p.salt, p.image_url, p.nutriscore_score, p.nutriscore_grade FROM c
il faut passer par la fonction getProduct() pour sécuriser contre les injections sql.

2023-07-09 22:42 UTC, lesageduvillage commented on infrastructure/controller/api.go
> +func (server *Server) getConsumedProducts(context *gin.Context) {
bah justement j'y ai pensé mais je suis pas sur que ce soit une bonne idée, car imagine l'user veut voir tous ses produits consommés on va pas faire un call api pour chaque jour

2023-07-09 22:43 UTC, lesageduvillage commented
il faut prendre en compte qu'il manque la quantité consommé dans les produits consommés

2023-07-10 17:36 UTC, AymanImhah submitted a review, later dismissed

2023-07-10 17:36 UTC, AymanImhah commented on infrastructure/controller/api.go
> +	ginEngine.POST("/product/consumed/user/:email", server.addConsumedProduct)
dans le post l'email est dans le body , avec le barcode

2023-07-10 17:44 UTC, merged