Domain entities
Master-Trolls-of-IT/PLIC-back pull request #2
Opened 2023-03-21 14:22 UTC by AymanImhah

Representing database tables as classes in Go.

2023-03-21 14:28 UTC, AkaMirai9 requested changes

2023-03-21 14:28 UTC, AkaMirai9 commented on domain/entities/tool.go
> +	Icon []byte `json:"image"`
Meme remarque qu'au dessus

2023-03-21 14:28 UTC, AkaMirai9 commented on domain/entities/user.go
> +	Basal_metabolism int          `json:"basal metabolism"`
l'espace dans basal metabolism ne risque pas d'être génant ?

2023-03-21 15:22 UTC, AkaMirai9 approved these changes

2023-03-21 15:28 UTC, Uzayur commented on domain/entities/day.go
> +	Kcal_count int       `json:"calories"`
Coding style

2023-03-21 15:28 UTC, Uzayur commented on domain/entities/recipe.go
> +	User_id       int       `json:"user_id"`
coding style

2023-03-21 15:28 UTC, Uzayur commented on domain/entities/recipe.go
> +	Total_steps   int       `json:"total_steps"`
coding style

2023-03-21 15:28 UTC, Uzayur commented on domain/entities/user.go
> +	Basal_metabolism int          `json:"basal_metabolism"`
coding style

2023-03-21 15:28 UTC, Uzayur commented on domain/entities/user.go
> +	athlete
Mets l'accent ici aussi

2023-03-21 15:28 UTC, Uzayur commented on domain/services/auth_service.go
> +	db_access ports.User_auth
coding style

2023-03-21 15:28 UTC, Uzayur commented on domain/services/auth_service.go
> +		db_access: db_access,
coding style

2023-03-21 15:28 UTC, Uzayur commented on domain/services/auth_service.go
> +func (service *auth_service) Login(id int) (entities.User, error) {
cm

2023-03-21 15:28 UTC, Uzayur commented on domain/services/auth_service.go
> +func (service *auth_service) Register(user entities.User) (int, error) {
cm

2023-03-21 15:28 UTC, Uzayur commented on domain/services/auth_service.go
> +	user_id, err := service.Register(user)
cm

2023-03-21 15:28 UTC, Uzayur commented on domain/services/auth_service.go
> +	return user_id, nil
cm

2023-03-30 08:44 UTC, lesageduvillage approved these changes

2023-03-30 09:56 UTC, Uzayur commented on infrastructure/repositories/database.go
> +			log.Fatalf("Fatal Error in connect_unix.go: %s environment variable not set.\n", k)
pas ouf les noms

2023-03-30 10:00 UTC, Uzayur approved these changes

2023-03-30 10:03 UTC, merged