Product/Adding-more-data
Master-Trolls-of-IT/PLIC-back pull request #27
Opened 2023-10-08 18:52 UTC by AymanImhah

Adding:  nutrients_serving, nutrients_value, nutrients_100g, quantity, serving_quantity, serving_size data "
Parsing and Adding:  nutrients_serving, nutrients_value, nutrients_100g, quantity, serving_quantity, serving_size data.

Example of the NEW product response: 
```
{
    "data": {
        "id": 73,
        "brand": "Gerblé",
        "name": "Gerblé - Sesame Cookie, 230g (8.2oz)",
        "nutrients": {
            "energyKj": 228,
            "energyKcal": 54,
            "fat": 2.1,
            "saturatedFat": 0.2,
            "carbohydrates": 0,
            "sugar": 2,
            "fiber": 0.5,
            "proteins": 1.2,
            "salt": 0.05
        },
        "nutrients_100g": {
            "energyKj": 1980,
            "energyKcal": 470,
            "fat": 18.3,
            "saturatedFat": 1.74,
            "carbohydrates": 0,
            "sugar": 17.4,
            "fiber": 4.35,
            "proteins": 10.4,
            "salt": 0.435
        },
        "nutrients_value": {
            "energyKj": 228,
            "energyKcal": 54,
            "fat": 2.1,
            "saturatedFat": 0.2,
            "carbohydrates": 0,
            "sugar": 2,
            "fiber": 0.5,
            "proteins": 1.2,
            "salt": 0.05
        },
        "nutrients_serving": {
            "energyKj": 228,
            "energyKcal": 54,
            "fat": 2.1,
            "saturatedFat": 0.2,
            "carbohydrates": 0,
            "sugar": 2,
            "fiber": 0.5,
            "proteins": 1.2,
            "salt": 0.05
        },
        "image_url": "https://images.openfoodfacts.org/images/products/317/568/001/1480/front_en.221.400.jpg",
        "nutriscore": {
            "score": 1,
            "grade": "b"
        },
        "ecoscore": "",
        "iswater": false,
        "quantity": "230g",
        "serving_quantity": 11.5,
        "serving_size": "11.5 g"
    },
    "message": "Les informations du produit ont été trouvées avec succès",
    "status": 200
}
```

2023-10-08 20:54 UTC, lesageduvillage commented on domain/entity/product.go
> +
ca sert a quoi le commentaire la

2023-10-08 20:55 UTC, lesageduvillage commented on infrastructure/controller/openFoodFacts_api.go
> +	//mappedNutrientsUnit := entity.NutrientsUnit{
la aussi

2023-10-08 21:08 UTC, AymanImhah commented on infrastructure/controller/openFoodFacts_api.go
> +	//mappedNutrientsUnit := entity.NutrientsUnit{
c'est l'implementation des unités de nutriments récupérés du parsing. Pour l'instant, j'ai tout commenté car je ne sais pas si cela nous sera utile coté front.

2023-10-09 08:00 UTC, AkaMirai9 requested changes

2023-10-09 08:00 UTC, AkaMirai9 commented on infrastructure/repository/product_repository.go
> +
Idem mettre un todo

2023-10-09 08:06 UTC, AkaMirai9 approved these changes

2023-10-09 08:07 UTC, merged